version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${ZOOKEEPER_DATA_PATH}:/var/lib/zookeeper/
  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA1_PORT}:${KAFKA1_PORT}
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: SSL://${KAFKA_HOST}:${KAFKA1_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: keystore/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: key_creds.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: key_creds.txt
      KAFKA_SSL_KEY_CREDENTIALS: key_creds.txt
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ${SECRET_DATA_PATH}:/etc/kafka/secrets
      - ${KAFKA1_DATA_PATH}:/var/lib/kafka/data
  kafka2:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA2_PORT}:${KAFKA2_PORT}
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: SSL://${KAFKA_HOST}:${KAFKA2_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: keystore/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: key_creds.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: key_creds.txt
      KAFKA_SSL_KEY_CREDENTIALS: key_creds.txt
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ${SECRET_DATA_PATH}:/etc/kafka/secrets
      - ${KAFKA2_DATA_PATH}:/var/lib/kafka/data
  kafka3:
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA3_PORT}:${KAFKA3_PORT}
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_ADVERTISED_LISTENERS: SSL://${KAFKA_HOST}:${KAFKA3_PORT}
      KAFKA_INTER_BROKER_LISTENER_NAME: SSL
      KAFKA_SSL_KEYSTORE_FILENAME: keystore/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: key_creds.txt
      KAFKA_SSL_TRUSTSTORE_FILENAME: truststore/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: key_creds.txt
      KAFKA_SSL_KEY_CREDENTIALS: key_creds.txt
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ${SECRET_DATA_PATH}:/etc/kafka/secrets
      - ${KAFKA3_DATA_PATH}:/var/lib/kafka/data